"""phase 7: workflow escalation fields

Revision ID: 52011ed7e2e7
Revises: e5f6a7b8c9d0
Create Date: 2026-08-01 22:41:43.430881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52011ed7e2e7'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_approval_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_workflow_runs_pending_approval_id', 'approval_requests', ['pending_approval_id'], ['id']
        )

    with op.batch_alter_table('workflow_step_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalated', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('escalation_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_step_runs', schema=None) as batch_op:
        batch_op.drop_column('escalation_reason')
        batch_op.drop_column('escalated')

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workflow_runs_pending_approval_id', type_='foreignkey')
        batch_op.drop_column('pending_approval_id')

    # ### end Alembic commands ###
